export const chapters = [
  {
    id: 'send',
    index: '00',
    label: 'The send',
    title: 'Made it safely.',
    copy: 'You tap send. A hidden world wakes up.',
    detail: 'Before the message can move, it is translated into data and split into small numbered packets—each carrying enough information to find its way.',
    fact: 'The whole journey begins in less time than a blink.',
    image: '/assets/concepts/01-send.jpg',
    align: 'left',
    layout: 'hero',
  },
  {
    id: 'home',
    index: '01',
    label: 'The first hop',
    title: 'Your room is only the beginning.',
    copy: 'Radio waves carry the packets a few metres to your router. It reads their destination, then opens a door to the wider network.',
    detail: 'Wi-Fi is not the internet. It is the first short bridge between your device and a chain of wired networks beyond your walls.',
    fact: 'First hop · approximately 3 ms',
    image: '/assets/concepts/01-send.jpg',
    align: 'right',
    layout: 'edge',
  },
  {
    id: 'city',
    index: '02',
    label: 'The city network',
    title: 'Under every street, a second city glows.',
    copy: 'Your packets join thousands of others, moving through neighborhood junctions and an internet provider’s high-capacity backbone.',
    detail: 'Routers repeat one small decision at every junction: which available path moves this packet closer to its address?',
    fact: 'Local network · approximately 12 ms',
    image: '/assets/concepts/02-city.jpg',
    align: 'right',
    layout: 'lower',
  },
  {
    id: 'ocean',
    index: '03',
    label: 'The long crossing',
    title: 'Light beneath the ocean.',
    copy: 'Across continents, the message becomes pulses of light racing through hair-thin strands of glass inside armoured submarine cables.',
    detail: 'Most international internet traffic travels under the sea—not through satellites. Repeaters restore the signal along the immense crossing.',
    fact: 'Ocean crossing · approximately 48 ms',
    image: '/assets/concepts/03-ocean.jpg',
    align: 'left',
    layout: 'upper',
  },
  {
    id: 'machine',
    index: '04',
    label: 'The data center',
    title: 'Inside the machine.',
    copy: 'In a data center, switches direct the packets while servers process the request. Encryption keeps the message unreadable along the way.',
    detail: 'Encryption hides the contents while routers still read the addressing metadata needed for delivery. The server prepares a response and sends fresh packets back into the network.',
    fact: 'Process and respond · approximately 21 ms',
    image: '/assets/concepts/04-datacenter.jpg',
    align: 'left',
    layout: 'edge',
  },
  {
    id: 'routing',
    index: '05',
    label: 'Traffic and recovery',
    title: 'The internet finds another way.',
    copy: 'Packets can take different routes. When a path is crowded—or one packet disappears—the network slows, reroutes, and sends what is missing again.',
    detail: 'They may arrive out of order. Reliability comes from sequence numbers, acknowledgements, and retransmission.',
    fact: 'Routing is adaptive, not predetermined.',
    image: '/assets/concepts/05-routing.jpg',
    align: 'left',
    layout: 'lower',
  },
  {
    id: 'reply',
    index: '06',
    label: 'The global relay',
    title: 'The reply',
    copy: 'The answer takes the same invisible highway home — another lap around the world.',
    detail: 'A fresh stream of encrypted packets leaves the server. Each route is independent, but every fragment is aimed at the same final address: you.',
    fact: 'One message · many routes · one destination',
    kind: 'globe',
    layout: 'globe',
  },
  {
    id: 'arrival',
    index: '07',
    label: 'Reassembly',
    title: 'Made it safely.',
    copy: 'At the destination, the packets return to order. Data becomes language again.',
    detail: 'One tap. Thousands of decisions. A journey across the physical world completed in milliseconds.',
    fact: 'So did the message.',
    image: '/assets/concepts/06-arrival.jpg',
    align: 'left',
    layout: 'arrival',
  },
]
